URL_SERVICE = "https://cnt-bcfd9ca9-936c-4d38-82d9-55b9a51ca6a7.containerhub.tripleten-services.com"
CREATE_USER_PATH = "/api/v1/users"
KITS_PATH = "/api/v1/kits"
KITS_TABLE_PATH = "/api/db/resources/kit_model.csv"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
